version: '3.8'

services:
  go-eth-service:
    container_name: go-eth-service
    image: golang:1.23
    working_dir: /go-eth
    volumes:
      - ./src:/go-eth
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - bridge-network
    command: bash -c "go mod download && go run main.go"

  mongo:
    container_name: mongo
    image: mongo:5.0
    ports:
      - "27017:27017"
    networks:
      - bridge-network

networks:
  bridge-network:
    name: go-eth_bridge-network
    driver: bridge
